version: '3.7'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ../:/var/www:delegated
      - ./nginx/:/etc/nginx/conf.d:delegated
      - ./nginx/vhosts:/etc/nginx/vhosts:delegated
      - ./nginx/logs:/var/log/nginx:delegated
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: php-fpm
      dockerfile: Dockerfile
    image: bitnami/php-fpm
    volumes:
      - ../:/var/www:delegated
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/40-custom.ini:delegated
      - ~/.ssh:/home/www-data/.ssh:delegated
  mariadb:
    image: yobasystems/alpine-mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=docker
  adminer:
    image: adminer
    environment:
      - ADMINER_DESIGN=hever
    volumes:
      - ./adminer/adminer.css:/var/www/html/designs/hever/adminer.css:delegated
